#!/bin/bash

if [ ! -f Dockerfile ]; then
    echo "Dockerfile not found!! "
    exit 1
fi

IMAGE=$(head -1 Dockerfile | sed -e 's/#//')
if [ -z  "$IMAGE" ]; then
    echo "Dockerfile not have any image name"
    exit 1
fi

docker build -t $IMAGE .  && docker push $IMAGE

